all:
	gcc q2_p1_socket.c -o p1_socket
	gcc q2_p2_socket.c -o p2_socket
	gcc q2_p1_fifo.c -o p1_fifo
	gcc q2_p2_fifo.c -o p2_fifo
	gcc q2_p1_shared_mem.c -o p1_shared_mem -lrt
	gcc q2_p2_shared_mem.c -o p2_shared_mem -lrt