all:
	gcc q1_a_semaphores.c -o q1_a_semaphores -lpthread
	gcc q1_a_strict_ordering.c -o q1_a_strict_ordering -lpthread
	gcc q1_b_semaphores.c -o q1_b_semaphores -lpthread
	gcc q1_b_strict_ordering.c -o q1_b_strict_ordering -lpthread